# Database Configuration (Shared with Laravel SQLite database)
spring.datasource.url=jdbc:sqlite:D:/College/Sem 4/OOP/Final Project/fitness-db/database/database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate / JPA configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# Set to 'none' because Laravel manages migrations and database schema structure
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080
